pipeline:
  run-test-suite:
    image: michalpodeszwa/docker-compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ./bin/drone-run-tests.sh api-tests
    when:
      event: [pull_request]

  publish-api-docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password, docker_email ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    repo: paralect/ship-api
    tags:
      - latest
      - ${DRONE_BRANCH}
    dockerfile: ./api/Dockerfile
    context: ./api
    when:
      branch: ["master", "production"]
      event: [push]
